export const radii = {
  "small.semiDefault": "0px",
  "small.default": "1px",
  "small.semiIncreased": "4px",
  "normal.semiDefault": "5px",
  "normal.default": "6px",
  "normal.semiIncreased": "8px",
  "medium.semiDefault": "10px",
  "medium.default": "12px",
  "medium.semiIncreased": "16px",
  "large.semiTiny": "20px",
  "large.tiny": "24px",
  "large.semiSmall": "28px",
  "large.small": "32px",
  "large.semiReduced": "40px",
  "large.reduced": "80px",
  "large.semiDefault": "122px",
  "large.default": "140px",
  "large.semiIncreased": "160px",
  "large.increased": "222px",
  "large.semiLarge": "240px",
  "large.large": "320px",
  "large.semiHuge": "999px",
  "large.huge": "2222px",
};
