export type * from '../icons.interfaces.js'

export * from './ArrowDown.icon.js'
export * from './ArrowLeft.icon.js'
export * from './ArrowRight.icon.js'
export * from './Back.icon.js'
export * from './Check.icon.js'
export * from './Close.icon.js'
export * from './DoubleArrow.icon.js'
export * from './DropDown.icon.js'
export * from './Facebook.icon.js'
export * from './FooterLogo.icon.js'
export * from './Logo.icon.js'
export * from './Menu.icon.js'
export * from './Vk.icon.js'
export * from './Wheel.icon.js'
export * from './Telegram.icon.js'
