export { revalidate } from '@blog/post-page'
export { dynamicParams } from '@blog/post-page'
export { generateStaticParams } from '@blog/post-page'
export { generateMetadata } from '@blog/post-page'
export { default } from '@blog/post-page'
