export { revalidate } from '@site/service-page'
export { dynamicParams } from '@site/service-page'
export { generateStaticParams } from '@site/service-page'
export { generateMetadata } from '@site/service-page'
export { default } from '@site/service-page'
