export const fontSizes = {
  // atom: '13px',
  // small: '14px',
  // normal: '16px',
  // big: '18px',
  // large: '22px',
  // xl: '28px',
  // extraLarge: '32px',
  // giant: '40px',
  // godzilla: '48px',
  // extra: '56px',
  'small.reduced': '10px',
  'small.semiDefault': '12px',
  'small.default': '13px',
  'small.semiIncreased': '14px',
  'normal.reduced': '16px',
  'normal.semiDefault': '18px',
  'normal.default': '22px',
  'normal.semiIncreased': '24px',
  'medium.reduced': '28px',
  'medium.semiDefault': '32px',
  'medium.default': '38px',
  'medium.semiIncreased': '40px',
  'medium.increased': '44px',
  'large.undefined': '52px',
  'large.semiTiny': '56px',
  'large.tiny': '60px',
  'large.semiSmall': '64px',
  'large.small': '72px',
  'large.semiReduced': '78px',
  'large.reduced': '80px',
  'large.semiDefault': '84px',
  'large.default': '94px',
  'large.semiIncreased': '96px',
  'large.increased': '108px',
  'large.semiLarge': '120px',
  'large.large': '124px',
  'large.semiHuge': '128px',
  'large.huge': '160px',
  'large.semiGiant': '216px',
}
