export const radii = {
  "small.semiDefault": "0px",
  "small.default": "1px",
  "small.semiIncreased": "4px",
  "normal.semiDefault": "5px",
  "normal.default": "6px",
  "normal.semiIncreased": "8px",
  "medium.semiDefault": "10px",
  "medium.default": "12px",
  "medium.semiIncreased": "16px",
  "large.tiny": "20px",
  "large.semiSmall": "24px",
  "large.small": "28px",
  "large.semiReduced": "32px",
  "large.reduced": "40px",
  "large.semiDefault": "80px",
  "large.default": "122px",
  "large.semiIncreased": "140px",
  "large.increased": "160px",
  "large.semiLarge": "222px",
  "large.large": "240px",
  "large.semiHuge": "320px",
  "large.huge": "2222px",
};
