export * from './2gis-categories.mapper.js'
export * from './2gis-goods-category-data.mapper.js'
export * from './2gis-goods-data.mapper.js'
export * from './2gis-offers.mapper.js'

export * from './yandex-categories.mapper.js'
export * from './yandex-goods-category-data-deep.mapper.js'
export * from './yandex-goods-category-data.mapper.js'
export * from './yandex-goods-data.mapper.js'
export * from './yandex-offers.mapper.js'
